FROM node:16.13.2
WORKDIR /usr/src/app/front
COPY postcss.config.js ./
COPY tailwind.config.js ./
COPY vite.config.js ./
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm install
COPY . .
EXPOSE 3000
#EXPOSE 35729
CMD [ "node", "build"]