FROM node:16.13.2 as build

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./
COPY postcss.config.js ./
COPY tailwind.config.js ./
COPY vite.config.js ./
RUN npm install
COPY . ./
RUN npm run build

ENV HOST=0.0.0.0
CMD [ "npm", "run", "dev"]